// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzphxcHf0SNRTYizVeeWOhqWeh7R1SuHs',
    appId: '1:1079253197285:android:69f3afa263d064af638f0c',
    messagingSenderId: '1079253197285',
    projectId: 'ecommerceapp-726fb',
    storageBucket: 'ecommerceapp-726fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1DoIAnctgAz78sWMU3PhthLpEj5nH7_c',
    appId: '1:1079253197285:ios:aef0de28faf62440638f0c',
    messagingSenderId: '1079253197285',
    projectId: 'ecommerceapp-726fb',
    storageBucket: 'ecommerceapp-726fb.firebasestorage.app',
    androidClientId: '1079253197285-q84295mcpcst1g5hrocprab9vjqmuobb.apps.googleusercontent.com',
    iosClientId: '1079253197285-1giu4u515r7vhb8soklqhgh68lknok40.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomApp',
  );

}